---
name: HTTP-MobileAgent-Plugin-Location
version: 0.0.2
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Add location fuctions to HTTP::MobileAgent
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  HTTP::MobileAgent::Plugin::XHTML: 0
  Test::Base: 0
  URI: 0
  URI::Escape: 0
  URI::QueryParam: 0
  version: 0
provides:
  HTTP::MobileAgent::Plugin::Location:
    file: lib/HTTP/MobileAgent/Plugin/Location.pm
    version: 0.0.2
  HTTP::MobileAgent::Plugin::Location::AreaObject:
    file: lib/HTTP/MobileAgent/Plugin/Location/AreaObject.pm
    version: 0.0.1
  HTTP::MobileAgent::Plugin::Location::LocationObject:
    file: lib/HTTP/MobileAgent/Plugin/Location/LocationObject.pm
    version: 0.0.1
  HTTP::MobileAgent::Plugin::Location::LocationObject::GCC:
    file: lib/HTTP/MobileAgent/Plugin/Location/LocationObject/GCC.pm
    version: 0.0.1
  HTTP::MobileAgent::Plugin::Location::LocationObject::LG:
    file: lib/HTTP/MobileAgent/Plugin/Location/LocationObject/LG.pm
    version: 0.0.1
  HTTP::MobileAgent::Plugin::Location::Support:
    file: lib/HTTP/MobileAgent/Plugin/Location/Support.pm
    version: 0.0.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
